In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.6 MB 10.7 MB/s eta 0:00:01
   -------------- ------------------------- 4.5/12.6 MB 11.2 MB/s eta 0:00:01
   -------------------- ------------------- 6.6/12.6 MB 10.6 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 10.3 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.6 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
val = [[1, 2, 3], [4, 5, 6]]
arr = np.array(val)

print(val)
print(arr)
print(type(arr))

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [13]:
import numpy as np
val = [[1, 2, 3], [4, 5, 6]]
arr = np.array(val[1])

print(arr[0])

4


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:5])

[1 2 3 4 5]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:7:2])

[2 4 6]


In [21]:
#Return every other element from the entire array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [22]:
#Create an array with data type string
import numpy as np

arr = np.array([1, 2, 3, 4], dtype = "S")

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [23]:
#Create an array with data type 4 bytes integer
import numpy as np

arr = np.array([1, 2, 3, 4], dtype = "i4")

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [24]:
#the copy is a new array, and the view is just a view of the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [26]:
#the base  attribute refers to the original object
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [27]:
#The shape of an array is the number of elements in each dimension
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)
